import {teachingReply} from '../engine/teaching-reply';
import {Match,Chess,input,pins,discoveries,forkTargets,type Square,type InputMove,type ChessSave} from '../engine/chess';
import {miniStart} from './bank';import {isPassedPawn} from './pawn-outcomes';import type {Skill} from './ledger';
export const miniKinds=['passer','weak-pawn','knight-game','rook-game','bishop-game','queen-game','opening','active-rook','pawn-defense','create-passer','mate-rook','mate-queen','safe-team','fork-game','pin-game','discovery-game','passing-game','prevent-game']as const;
export type MiniKind=typeof miniKinds[number];
export const miniNames:Record<MiniKind,string>={passer:'Promote the pawn','weak-pawn':'Attack a weak pawn','knight-game':'Knight journey','rook-game':'Rook journey','bishop-game':'Bishop journey','queen-game':'Queen journey',opening:'Build a safe opening','active-rook':'Activate and attack','pawn-defense':'Defend the pawn','create-passer':'Create and escort','mate-rook':'King and Rook mate','mate-queen':'King and Queen mate','safe-team':'Protect the Queen','fork-game':'Use a fork','pin-game':'Use a pin','discovery-game':'Use a revealed ray','passing-game':'Catch the passing pawn','prevent-game':'Stop the promotion threat'};
export const miniSkill:Record<MiniKind,Skill>={passer:'create-passer','weak-pawn':'weakness','knight-game':'n','rook-game':'r','bishop-game':'b','queen-game':'q',opening:'team','active-rook':'activity','pawn-defense':'pawn-defense','create-passer':'create-passer','mate-rook':'mate','mate-queen':'stalemate','safe-team':'threat','fork-game':'fork','pin-game':'pin','discovery-game':'discovery','passing-game':'en-passant','prevent-game':'prevent'};
export function miniForSkill(skill:Skill):MiniKind{return ({p:'passer',n:'knight-game',r:'rook-game',b:'bishop-game',q:'queen-game',k:'pawn-defense',team:'opening',castle:'opening',promotion:'passer','en-passant':'passing-game',activity:'active-rook',weakness:'weak-pawn',passer:'create-passer','create-passer':'create-passer','pawn-defense':'pawn-defense','active-king':'pawn-defense',mate:'mate-rook',stalemate:'mate-queen',check:'pawn-defense',prevent:'prevent-game',threat:'safe-team',fork:'fork-game',pin:'pin-game',discovery:'discovery-game'}as Record<Skill,MiniKind>)[skill];}
const starts:Record<MiniKind,string>={passer:miniStart,'weak-pawn':'7k/8/8/8/2P1p3/2K5/8/8 w - - 0 1','knight-game':'7k/7p/8/3p4/8/8/8/1N5K w - - 0 1','rook-game':'7k/7p/8/3p4/8/8/P7/R6K w - - 0 1','bishop-game':'7k/7p/8/8/5p2/8/8/2B4K w - - 0 1','queen-game':'7k/7p/8/1p6/8/8/8/3Q3K w - - 0 1',opening:new Chess().fen(),'active-rook':'7k/5p1p/8/8/8/8/P7/R6K w - - 0 1','pawn-defense':'7k/8/8/8/2P3r1/2K5/8/8 w - - 0 1','create-passer':'7k/8/2pp4/2PP4/2K5/8/8/8 w - - 0 1','mate-rook':'7k/R4K2/8/8/8/8/8/8 w - - 0 1','mate-queen':'7k/8/1Q3K2/8/8/8/8/8 w - - 0 1','safe-team':'3rk3/8/8/8/3Q4/8/P7/K7 w - - 0 1','fork-game':'4k3/8/3r3r/8/8/4N3/8/4K3 w - - 0 1','pin-game':'4k3/4n2p/8/8/1B6/8/8/K2R4 w - - 0 1','discovery-game':'7k/8/8/8/4r3/8/4N3/K3R3 w - - 0 1','passing-game':'7k/3p4/8/4P3/8/8/8/K7 w - - 0 1','prevent-game':'7k/8/8/8/8/6p1/R7/K7 w - - 0 1'};
const firstReplies:Partial<Record<MiniKind,InputMove>>={'knight-game':{from:'h7',to:'h6'},'rook-game':{from:'h7',to:'h6'},'queen-game':{from:'h7',to:'h6'},'active-rook':{from:'h7',to:'h6'},'pawn-defense':{from:'g4',to:'c4'},'fork-game':{from:'d6',to:'d8'},'pin-game':{from:'h7',to:'h6'},'discovery-game':{from:'h8',to:'g8'},'passing-game':{from:'d7',to:'d5'},'prevent-game':{from:'h8',to:'h7'}};
const mirror=(s:Square)=>(String.fromCharCode(104-(s.charCodeAt(0)-97))+s[1])as Square;
export function miniInput(move:InputMove,variant:number):InputMove{return variant?{...move,from:mirror(move.from),to:mirror(move.to)}:move;}
function start(kind:MiniKind,variant:number){if(!variant)return starts[kind];if(kind==='opening')return'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2';const c=new Chess(starts[kind]),flipped=new Chess();flipped.clear();for(const p of c.board().flat())if(p)flipped.put({type:p.type,color:p.color},mirror(p.square));return flipped.fen();}
export class MiniGame{
 constructor(public kind:MiniKind='passer',public variant:0|1=0){this.match=new Match(start(kind,variant));}match:Match;get chess(){return this.match.chess;}get rounds(){return this.chess.history({verbose:true}).filter(m=>m.color==='w').length;}
 get outcome(){const c=this.chess,h=c.history({verbose:true});
  if(this.kind==='passer'||this.kind==='weak-pawn'){if(c.isCheckmate())return c.turn()==='b'?'won':'retry';if(this.rounds>=3&&(this.kind==='passer'?h.some(m=>m.color==='w'&&!!m.promotion):c.board().flat().some(p=>p?.color==='w'&&p.type!=='k')&&h.some(m=>m.color==='w'&&m.captured==='p')))return'won';return c.isGameOver()||this.rounds>=12?'review':'playing';}
  if(this.kind.startsWith('mate-'))return c.isCheckmate()?c.turn()==='b'?'won':'retry':c.isGameOver()||this.rounds>=16?'review':'playing';
  const replay=new Chess(this.match.start);let fork=false,pin=false,discovery=false,created=false,escorted=false,active=false,prevented=false;const minor=new Set<string>(),identities=new Map<Square,string>();for(const p of replay.board().flat())if(p?.color==='w'&&['n','b'].includes(p.type))identities.set(p.square,p.square);for(const m of h){const identity=identities.get(m.from);identities.delete(m.from);identities.delete(m.to);if(identity)identities.set(m.to,identity);const before=new Chess(replay.fen());replay.move(input(m));if(m.color!=='w')continue;fork ||= forkTargets(replay,m.to).length>=2;pin ||= pins(replay,'w').some(p=>p.attacker===m.to)&&!pins(before,'w').length;discovery ||= discoveries(before,replay,m).length>0;created ||= m.piece==='p'&&!isPassedPawn(before,m.from)&&isPassedPawn(replay,m.to);escorted ||= replay.board().flat().some(p=>p?.color==='w'&&p.type==='p'&&isPassedPawn(replay,p.square)&&replay.attackers(p.square,'w').some(s=>replay.get(s)?.type==='k'));active ||= m.piece==='r'&&Number(m.to[1])>=5;prevented ||= replay.get(this.variant?'b2':'g2')?.color==='w'&&replay.get(this.variant?'b3':'g3')?.color==='b';if(identity&&m.color==='w')minor.add(identity);}
  const owns=(role:string)=>c.board().flat().some(p=>p?.color==='w'&&p.type===role),capture=h.some(m=>m.color==='w'&&m.captured),queenSafe=owns('q')&&c.board().flat().every(p=>p?.color!=='w'||p.type!=='q'||c.attackers(p.square,'b').length===0);let won=false;
  if(this.kind==='opening')won=h.some(m=>m.color==='w'&&(m.flags.includes('k')||m.flags.includes('q')))&&minor.size>=2&&['d4','e4','d5','e5'].some(s=>c.get(s as Square)?.type==='p'&&c.get(s as Square)?.color==='w');
  else if(this.kind==='passing-game')won=owns('p')&&h.some(m=>m.color==='w'&&m.flags.includes('e'));
  else if(this.kind==='prevent-game')won=owns('r')&&prevented&&h.some(m=>m.color==='w'&&m.piece==='r'&&m.captured==='p');
  else if(this.kind==='create-passer')won=created&&escorted&&h.some(m=>m.color==='w'&&!!m.promotion);
  else if(this.kind==='pawn-defense')won=owns('p')&&capture&&escorted;
  else if(this.kind==='active-rook')won=owns('r')&&h.some(m=>m.color==='w'&&m.piece==='r'&&m.captured==='p')&&active;
  else if(this.kind==='safe-team')won=queenSafe&&h.filter(m=>m.color==='w'&&m.piece==='q').length>=2;
  else if(this.kind==='fork-game')won=fork&&h.some(m=>m.color==='w'&&m.piece==='n'&&m.captured==='r')&&owns('n');
  else if(this.kind==='pin-game')won=pin&&h.some(m=>m.color==='w'&&m.piece==='r'&&m.captured==='n')&&owns('r');
  else if(this.kind==='discovery-game')won=discovery&&h.some(m=>m.color==='w'&&m.piece==='r'&&m.captured==='r')&&owns('r');
  else{const role=({'knight-game':'n','rook-game':'r','bishop-game':'b','queen-game':'q'}as Record<string,string>)[this.kind];won=owns(role)&&h.some(m=>m.color==='w'&&m.piece===role&&m.captured)&&h.filter(m=>m.color==='w'&&m.piece===role).length>=2;}
  if(won&&this.rounds>=3&&(c.turn()==='w'&&!c.isCheck()||c.isGameOver()&&(!c.isCheckmate()||c.turn()==='b')))return'won';return c.isGameOver()||this.rounds>=12?'review':'playing';
 }
 play(m:InputMove){if(this.chess.turn()!=='w'||this.outcome!=='playing')return null;this.match.beginRound();const played=this.match.move(m);if(!played)this.match.undoRound();return played;}
 reply(){if(this.chess.turn()!=='b'||this.chess.isGameOver())return null;const opening=this.variant?[{from:'b8',to:'c6'},{from:'g8',to:'f6'},{from:'f8',to:'c5'}]:[{from:'e7',to:'e5'},{from:'b8',to:'c6'},{from:'g8',to:'f6'},{from:'f8',to:'c5'}];const scripted=this.kind==='opening'?opening[this.rounds-1]as InputMove|undefined:this.rounds===1?this.kind==='weak-pawn'&&this.variant?{from:'e4',to:'e3'}as InputMove:firstReplies[this.kind]:undefined,planned=scripted?miniInput(scripted,this.kind==='opening'?0:this.variant):null;const m=planned&&this.chess.moves({verbose:true}).some(m=>m.from===planned.from&&m.to===planned.to)?planned:teachingReply(this.chess);return m?this.match.move(m):null;}
 undo(){return this.match.undoRound();}save(){return{version:1,kind:this.kind,variant:this.variant,match:this.match.save()};}
 static restore(raw:unknown){try{const v=raw as {version:number;kind:MiniKind;variant?:number;match:ChessSave};if(v?.version!==1||!miniKinds.includes(v.kind)||v.variant!==undefined&&v.variant!==0&&v.variant!==1)return null;const match=Match.restore(v.match),game=new MiniGame(v.kind,(v.variant??0)as 0|1);if(!match||match.start!==game.match.start)return null;game.match=match;return game;}catch{return null;}}
}
