import type {InputMove, OpponentTier} from './chess';
import {curriculumLessons} from './curriculum';
export type Ladder='discover'|'apply'|'independent'|'plan'|'mixed';
export type Goal={kind:'move'|'capture'|'defend'|'check'|'escape-check'|'fork'|'pin'|'discovery'|'mate'|'castle'|'promotion'|'en-passant';move?:InputMove;square?:string;targets?:string[];piece?:'p'|'n'|'b'|'r'|'q'|'k'};
export type Lesson={id:string;title:string;story:string;fen:string;ladder:Ladder;pieceCount:number;choices:number;planningDepth:number;hintTier:0|1|2|3;goal:Goal;setup?:InputMove;setupGoal?:Goal;reply?:InputMove;hint:string[];boss?:boolean};
const m=(from:InputMove['from'],to:InputMove['to'],promotion?:InputMove['promotion']):InputMove=>({from,to,...(promotion?{promotion}:{})});
// Every FEN is a legal chess position. Goals inspect the resulting board; chess.js decides legality.
const previewLessons:Lesson[]=[
 {id:'rook-road',title:'Clear the road',story:'Move the rook to guard the road.',fen:'4k3/8/8/8/8/8/8/R3K3 w Q - 0 1',ladder:'discover',pieceCount:3,choices:16,planningDepth:1,hintTier:3,goal:{kind:'move',move:m('a1','a4'),square:'a4'},hint:['The rook travels in straight lines.','Look up the a-file.','Move a1 to a4.']},
 {id:'castle-shelter',title:'King to shelter',story:'Help the king castle safely.',fen:'4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1',ladder:'discover',pieceCount:4,choices:26,planningDepth:1,hintTier:3,goal:{kind:'castle',move:m('e1','g1')},hint:['The king and rook can move together.','Move the king two squares toward the rook.','Move e1 to g1.']},
 {id:'knight-fork',title:'Two guards at once',story:'Fork both guards, watch one move, then capture the other.',fen:'4k3/8/3r3r/8/8/4N3/8/4K3 w - - 0 1',ladder:'plan',pieceCount:5,choices:11,planningDepth:2,hintTier:1,setup:m('e3','f5'),setupGoal:{kind:'fork',targets:['d6','h6']},reply:m('d6','d8'),goal:{kind:'capture',square:'h6',piece:'n',move:m('f5','h6')},hint:['A knight can threaten two guards.','After one moves away, take the other.','Jump e3 to f5, then f5 to h6.']},
 {id:'guard-reply',title:'Follow the guard',story:'A rook guard retreats toward the king. Follow it and hold it in place.',fen:'7k/8/8/8/8/8/4r3/R1K5 w - - 0 1',ladder:'plan',pieceCount:4,choices:10,planningDepth:2,hintTier:1,setup:m('a1','a2'),setupGoal:{kind:'move',square:'a2',piece:'r'},goal:{kind:'pin',square:'e8',move:m('a2','a8')},reply:m('e2','e8'),hint:['Move the rook to the second rank to challenge the guard.','The guard retreats; follow along the a-file.','Move a1 to a2, then a2 to a8.']},
 {id:'promotion',title:'Choose a new piece',story:'Reach the far side and choose a piece.',fen:'4k3/P7/8/8/8/8/8/4K3 w - - 0 1',ladder:'discover',pieceCount:3,choices:9,planningDepth:1,hintTier:3,goal:{kind:'promotion',square:'a8',move:m('a7','a8','q')},hint:['The pawn is one step away.','Promotion offers four choices.','Move a7 to a8.']},
 {id:'en-passant',title:'The passing pawn',story:'Catch the pawn as it passes.',fen:'4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 1',ladder:'discover',pieceCount:4,choices:7,planningDepth:1,hintTier:3,goal:{kind:'en-passant',move:m('e5','d6')},hint:['A pawn just moved two squares.','Capture into the empty square behind it.','Move e5 to d6.']},
 {id:'pin',title:'Hold the guard',story:'Pin the guard to its king.',fen:'4k3/4r3/8/8/8/8/8/K2R4 w - - 0 1',ladder:'discover',pieceCount:4,choices:16,planningDepth:1,hintTier:3,goal:{kind:'pin',move:m('d1','e1'),square:'e7'},hint:['A line piece can hold a guard in place.','Line the rook up with the enemy king.','Move d1 to e1.']},
 {id:'discovery',title:'Reveal the ray',story:'Move the knight and reveal the rook attack.',fen:'4k3/8/8/8/4r3/8/4N3/K3R3 w - - 0 1',ladder:'discover',pieceCount:5,choices:15,planningDepth:1,hintTier:3,goal:{kind:'discovery',move:m('e2','c3'),square:'e4'},hint:['A knight blocks your rook.','Move it off the e-file.','Move e2 to c3.']},
 {id:'mate',title:'Protect the castle',story:'Find the final safe attack.',fen:'7k/6pp/5Q2/8/8/8/8/K7 w - - 0 1',ladder:'discover',pieceCount:5,choices:26,planningDepth:1,hintTier:3,goal:{kind:'mate',move:m('f6','f8')},hint:['The enemy king has few exits.','Look for a protected queen move.','Move f6 to f8.']},
];
const byId=new Map([...previewLessons,...curriculumLessons].map(l=>[l.id,l]));
export const previousOrder=['rook-road','rook-capture','rook-guard','bishop-path','bishop-rescue','bishop-cover','queen-rays','queen-rescue','queen-fork','king-step','give-check','king-escape','king-safe','castle-shelter','castle-friends','castle-other-side','promotion','promotion-capture','promotion-new-road','en-passant','en-passant-right','en-passant-new','knight-fork','guard-reply','pin','pin-diagonal','pin-light','discovery','discovery-diagonal','discovery-rook','mate','mate-rook','mate-light','stalemate-choice','opening-center','opening-develop','opening-shelter'];
const order=['rook-road','rook-capture','rook-guard','bishop-path','bishop-rescue','bishop-cover','queen-rays','queen-diagonal','queen-rescue','queen-diagonal-rescue','queen-fork','king-step','give-check','king-escape','king-capture-check','king-block-check','king-safe','castle-shelter','castle-friends','castle-other-side','promotion','promotion-capture','promotion-new-road','en-passant','en-passant-right','en-passant-new','knight-fork','guard-reply','pin','pin-diagonal','pin-light','discovery','discovery-diagonal','discovery-rook','mate','mate-rook','mate-light','stalemate-choice','opening-center','opening-develop','opening-mini-center','opening-shelter','opening-mini-shelter'];
export const lessons:Lesson[]=order.map(id=>{const lesson=byId.get(id);if(!lesson)throw new Error(`Missing lesson ${id}`);return lesson;});
export const fullGameTiers:OpponentTier[]=['gentle','steady','challenge'];
