import{test}from'node:test';import assert from'node:assert/strict';
import{ChapterGame,initial,legal,solution,same,validState,enemyMove,threats}from'../chapter/src/rules.ts';
test('all six lessons have a playable winning route, including the explicit helper demonstration',()=>{for(let i=0;i<6;i++){const g=new ChapterGame(i);if(i===1){assert.equal(legal(g.state,g.state.pieces[0]).length,0);assert(g.openPath());}const path=solution(g.state);assert(path,`level ${i}`);for(const m of path){assert(g.move(m));g.reply();assert.notEqual(g.state.status,'lost');}assert.equal(g.state.status,'won');console.log('Lesson',i+1,path);}});
test('pawn walks forward into empty cells and captures only enemy diagonally',()=>{const g=new ChapterGame(2),p=g.state.pieces[0];assert(legal(g.state,p).some(q=>same(q,{x:2,y:3})));assert(legal(g.state,p).some(q=>same(q,{x:3,y:3})));assert(!legal(g.state,p).some(q=>same(q,{x:1,y:3})));assert(!g.move({id:'a',to:{x:2,y:5}}));g.state.pieces[1].x=2;assert(!legal(g.state,p).some(q=>same(q,{x:2,y:3})));});
test('double step only from unmoved starting rank with both cells empty',()=>{const g=new ChapterGame(4),p=g.state.pieces[0];assert(legal(g.state,p).some(q=>q.y===2));p.moved=true;assert(!legal(g.state,p).some(q=>q.y===2));p.moved=false;g.state.pieces.push({id:'block',x:2,y:3,side:'friend',moved:false});assert.equal(legal(g.state,p).length,0);g.state.pieces[1].y=2;assert(legal(g.state,p).some(q=>q.y===3));assert(!legal(g.state,p).some(q=>q.y===2));});
test('enemy captures downwards and loss is reversible as a complete round',()=>{const g=new ChapterGame(5);g.state.pieces[2].x=2;g.state.pieces[2].y=2;const before=g.snapshot;assert(g.move({id:'a',to:{x:1,y:3}}));assert.equal(enemyMove(g.state)?.id,'e');g.reply();assert.equal(g.state.status,'lost');assert(g.undo());assert.deepEqual(g.state,before);assert(threats(g.state).some(p=>p.x===1&&p.y===3));});
test('undo cancels logical pending enemy turn and preserves complete snapshots',()=>{const g=new ChapterGame(3),before=g.snapshot;g.move({id:'a',to:{x:2,y:3}});g.undo();assert.equal(g.reply(),null);assert.deepEqual(g.state,before);});
test('serialized progress validates shape and cannot restore overlapping or foreign pieces',()=>{const s=initial(5);assert(validState(JSON.parse(JSON.stringify(s)),5));s.pieces[1].x=s.pieces[0].x;assert(!validState(s,5));assert(!validState({},0));assert(!validState(initial(1),3));});
test('a captured pawn is removed and the capturer occupies its cell',()=>{const g=new ChapterGame(2);const r=g.move({id:'a',to:{x:3,y:3}});assert.equal(r?.captured?.id,'e');assert.equal(g.state.pieces.length,1);assert(same(g.state.pieces[0],{x:3,y:3}));assert.equal(g.state.status,'won');assert.equal(g.reply(),null);});
