import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Chess,bestMove,opponentTiers,status,type InputMove} from '../chapter/src/engine/chess.ts';
import {lessons} from '../chapter/src/engine/lessons.ts';
import {Session} from '../chapter/src/engine/session.ts';
const lesson=(id:string)=>lessons.find(l=>l.id===id)!;
test('castling rejects check, crossing attack, and lost king/rook rights',()=>{
 const checked=new Chess('4r1k1/8/8/8/8/8/8/R3K2R w KQ - 0 1');assert(checked.isCheck());assert(!checked.moves({square:'e1'}).includes('O-O'));assert(!checked.moves({square:'e1'}).includes('O-O-O'));
 const crossed=new Chess('4kr2/8/8/8/8/8/8/R3K2R w KQ - 0 1');assert(!crossed.isCheck());assert(!crossed.moves({square:'e1'}).includes('O-O'));assert(crossed.moves({square:'e1'}).includes('O-O-O'));
 const king=new Chess('4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1');for(const move of [{from:'e1',to:'f1'},{from:'e8',to:'f8'},{from:'f1',to:'e1'},{from:'f8',to:'e8'}])king.move(move);assert(!king.moves({square:'e1'}).includes('O-O'));assert(!king.moves({square:'e1'}).includes('O-O-O'));
 const rook=new Chess('4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1');for(const move of [{from:'h1',to:'h2'},{from:'e8',to:'f8'},{from:'h2',to:'h1'},{from:'f8',to:'e8'}])rook.move(move);assert(!rook.moves({square:'e1'}).includes('O-O'));assert(rook.moves({square:'e1'}).includes('O-O-O'));
});
test('all promotion choices complete the outcome, and equivalent castling is accepted',()=>{for(const promotion of ['q','r','b','n'] as const){const s=new Session(lesson('promotion'));assert(s.play({from:'a7',to:'a8',promotion}));assert.equal(s.finished,true);assert.equal(s.chess.get('a8')?.type,promotion);}const castle=new Session(lesson('castle-shelter'));assert(castle.play({from:'e1',to:'c1'}));assert.equal(castle.finished,true);});
test('en passant expires after one reply and cannot expose the king',()=>{const c=new Chess('4k3/3p4/8/4P3/8/8/8/4K3 b - - 0 1');c.move({from:'d7',to:'d5'});assert(c.moves({square:'e5'}).includes('exd6'));c.move({from:'e1',to:'f1'});c.move({from:'e8',to:'f8'});assert(!c.moves({square:'e5'}).includes('exd6'));const pinned=new Chess('k3r3/8/8/3pP3/8/8/8/4K3 w - d6 0 1');assert(!pinned.moves({square:'e5'}).includes('exd6'));});
test('draw and undo survive save; corrupt round and completion metadata are rejected',()=>{const s=new Session();for(let i=0;i<2;i++){assert(s.play({from:'g1',to:'f3'}));assert(s.reply({from:'g8',to:'f6'}));assert(s.play({from:'f3',to:'g1'}));assert(s.reply({from:'f6',to:'g8'}));}assert.equal(status(s.chess),'repetition');const restored=Session.restore(s.save());assert(restored);assert.equal(restored.end,'repetition');assert(restored.undo());assert.equal(restored.end,'playing');assert.equal(restored.turn,'w');const save=s.save();assert.equal(Session.restore({...save,finished:true}),null);assert.equal(Session.restore({...save,match:{...save.match,rounds:[0]}}),null);const puzzle=new Session(lesson('rook-road'));const bad=puzzle.save();assert.equal(Session.restore({...bad,finished:true}),null);});
test('invalid scripted reply falls back to a legal move; search obeys node caps',()=>{const s=new Session(lesson('guard-reply'));assert(s.play(lesson('guard-reply').setup!));const reply=s.reply({from:'a8',to:'a7'} as InputMove);assert(reply);assert.equal(s.turn,'w');for(const tier of ['gentle','steady','challenge'] as const){const c=new Chess(),stats={nodes:0};const fen=c.fen(),move=bestMove(c,tier,stats);assert(move);assert(stats.nodes>0&&stats.nodes<=opponentTiers[tier].nodes,`${tier}: ${stats.nodes}`);assert.equal(c.fen(),fen);}});
