// Recorded lines supplied by the user. Exact text keeps captions and audio together.
export const recordings:Record<string,string>={
  "This little hero is your pawn. Watch it move one square forward. Now you try! Tap your pawn, then the square ahead.": "level-1-guide.wav",
  "You found Toothless! Thank you! Will you come with me?": "level-1-done.wav",
  "Toothless spots a friend on the path. Can your pawn move forward with someone in the way?": "level-2-intro.wav",
  "A pawn cannot jump over another piece. Tap your friend. Let us ask him to clear the path.": "level-2-guide.wav",
  "The path was clear, so your pawn could follow. Come on! Our friend has spotted something in the mist.": "level-2-done.wav",
  "Oh! The mist has put a spell on a guard. Capture his piece to break the spell and set him free!": "level-3-intro.wav",
  "Pawns move straight ahead, but capture diagonally. That means one square forward and one to the side. Watch, then try!": "level-3-guide.wav",
  "The guard is free! Move straight. Capture diagonally. Two different moves!": "level-3-done.wav",
  "Another guard is coming through the garden. Toothless stays close. This time, you choose the way.": "level-4-intro.wav",
  "Look before you move. Can you capture yet, or do you need to move closer? Watch what changes after the guard moves.": "level-4-guide.wav",
  "You moved closer, then spotted your capture! Beyond the garden, a golden star lights the path.": "level-4-done.wav",
  "The star is just ahead! Your pawn is on its starting square. It has not moved yet.": "level-5-intro.wav",
  "On its first move, a pawn may go one or two squares forward. For two steps, both squares must be empty. Watch, then choose!": "level-5-guide.wav",
  "You reached the star! After a pawn has moved, it cannot take that two-square first step again.": "level-5-done.wav",
  "The village gate is near! But two guards are still under the spell. You have two pawns to help them. Toothless is counting on you!": "level-6-intro.wav",
  "Choose one pawn to move each turn. Then watch the guards. Look for captures, and keep your pawns safe. I am here if you need help.": "level-6-guide.wav",
  "Both guards are free. The gate swings open! You and Toothless did it together. Here is your dragon badge!": "level-6-done.wav",
  "Tap your pawn first.": "choose-pawn.wav",
  "Now tap a square to move to.": "choose-square.wav",
  "Your turn. Look before you move.": "your-turn.wav",
  "The guards are moving. Watch closely.": "enemy-turn.wav",
  "Not that square. Try another, or tap me for help.": "invalid-move.wav",
  "The gold borders show where you can move.": "hint-moves.wav",
  "Warning marks show where a guard could capture your pawn.": "hint-danger.wav",
  "Look at this pawn and the little star.": "hint-next.wav",
  "Back to your last turn. Try a new plan!": "undo.wav",
  "That is okay. Tap Undo. We can try together.": "try-again.wav",
  "Listen\u2026 Someone is hiding in the mist. It is a little dragon! His name is Toothless. \u201cI cannot find my way home. Will you help me?\u201d A path of stones leads into the forest. Your adventure starts with one small step.": "chapter-1-intro-liam.mp3"
};
