import Phaser from 'phaser';
import {DragonCompanion} from './dragon';
import {ForestCast} from './forest-cast';
import {ForestEffects} from './forest-effects';
import {forestTier,forestMove} from './forest-adventure';
import {Atmosphere} from '../../shrine/src/atmosphere';
import {boardCells,boardSize,kind,goalCell,forkTargets,legal,threats,same,type State,type Cell,type Piece,type Move} from './rules';
export class Garden extends Phaser.Scene{
 forest=false;progress:readonly boolean[]=[];gear:Partial<Record<'pawn'|'knight'|'rook','apprentice'|'guardian'|'master'>>={};
 ready!:()=>void;layout!:(x:number,y:number,c:number)=>void;reduced=false;
 private backdrop?:Phaser.GameObjects.Image;private cast?:ForestCast;private forestFx?:ForestEffects;private tiles:Phaser.GameObjects.Image[]=[];
 private bg!:Phaser.GameObjects.Image;private stones!:Phaser.GameObjects.Graphics;private shadows!:Phaser.GameObjects.Graphics;
 private atmosphere!:Atmosphere;private dragon!:DragonCompanion;private pieces=new Map<string,Phaser.GameObjects.Sprite>();private labels:Phaser.GameObjects.Text[]=[];
 private dataState?:State;private selected:string|null=null;private help=0;private danger=false;private best:Move|null=null;
 private ox=0;private oy=0;private cell=64;private moving=false;private finishes=new Set<()=>void>();private ghost?:Phaser.GameObjects.Sprite;
 constructor(){super('Garden');}
 preload(){const b=import.meta.env.BASE_URL;if(this.forest){for(const [key,file]of [['forest-env','environment'],['forest-stone','stone'],['forest-pawn','pawns'],['forest-knight','knights'],['forest-rook','rook-upgrades']])if(key==='forest-rook')this.load.svg(key,b+'rook-grove-v2/rook-towers.svg',{width:512,height:512});else this.load.image(key,b+'rook-grove-v2/'+file+'.webp');}else this.load.image('garden',b+'environment/shrine.png');this.load.image('dragon-atlas',b+'characters/dragon-a-v3.png');if(!this.forest)this.load.spritesheet('heroes',b+'characters/heroes.png',{frameWidth:512,frameHeight:512});this.load.on('loaderror',()=>{document.getElementById('load-error')!.hidden=false;});}
 create(){if(this.forest){this.backdrop=this.add.image(0,0,'forest-env').setDepth(-2).setAlpha(.6);this.cast=new ForestCast(this);this.forestFx=new ForestEffects(this);}this.bg=this.add.image(0,0,this.forest?'forest-env':'garden').setDepth(-1);this.stones=this.add.graphics().setDepth(this.forest?2:1);this.shadows=this.add.graphics().setDepth(this.forest?2.5:2);this.atmosphere=new Atmosphere(this);this.dragon=new DragonCompanion(this);this.scale.on('resize',()=>{this.cancel();this.draw();});this.ready();}
 dragonCue(action:'flap'|'hint'|'happy'){this.dragon?.cue(action);}
 point(p:Cell){return{x:this.ox+(p.x+.5)*this.cell,y:this.oy+(p.y+.5)*this.cell};}
 sync(s:State,selected:string|null,help:number,danger:boolean,best:Move|null=null){this.dataState=structuredClone(s);this.selected=selected;this.help=help;this.danger=danger;this.best=best;this.draw();}
 private label(x:number,y:number,text:string,color='#fff0bd',size=17){this.labels.push(this.add.text(x,y,text,{fontFamily:'sans-serif',fontSize:size,color,fontStyle:'bold'}).setOrigin(.5).setDepth(this.forest?7:3));}
 private draw(){if(!this.dataState||!this.stones)return;const s=this.dataState,w=this.scale.width,h=this.scale.height,{width:WIDTH,height:HEIGHT}=boardSize(s.level),cells=boardCells(s.level);const stageWidth=Math.min(w,h/1.5,560),stageHeight=stageWidth*1.5,stageX=(w-stageWidth)/2,stageY=(h-stageHeight)/2;
 if(this.forest){this.cell=Math.min((w-16)/WIDTH,(h-144)/HEIGHT,65);this.ox=(w-this.cell*WIDTH)/2;this.oy=(h-this.cell*HEIGHT)/2;this.backdrop!.setPosition(w/2,h/2).setScale(Math.max(w/1024,h/1536));this.bg.setPosition(w/2,h/2).setDisplaySize(stageWidth,stageHeight);this.forestFx!.layout(this.ox,this.oy,this.cell*WIDTH,this.cell*HEIGHT);}else{this.cell=Math.min((w-38)/WIDTH,(h-125)/HEIGHT,77);this.ox=(w-this.cell*WIDTH)/2;this.oy=83+(h-105-this.cell*HEIGHT)/2;this.bg.setPosition(w/2,h/2).setScale(Math.max(w/1536,h/1024));}
 this.layout(this.ox,this.oy,this.cell);this.atmosphere.layout(this.ox,this.oy,this.cell*HEIGHT);this.stones.clear();this.labels.forEach(x=>x.destroy());this.labels=[];
 const piece=s.pieces.find(p=>p.id===this.selected),moves=piece?legal(s,piece):[],danger=threats(s);
 this.tiles.forEach((t,i)=>t.setVisible(this.forest&&i<cells.length));
 for(const [i,p] of cells.entries()){const q=this.point(p),r=this.cell/2-3,bad=this.danger&&danger.some(a=>same(a,p)),good=this.help>0&&moves.some(a=>same(a,p));if(this.forest){const tile=this.tiles[i]??(this.tiles[i]=this.add.image(0,0,'forest-stone').setDepth(1));tile.setVisible(true).setPosition(q.x,q.y).setDisplaySize(this.cell,this.cell).setAngle(i%5===0?180:i%3===0?90:0);if(bad)this.stones.fillStyle(0xa66e87,.25).fillRoundedRect(q.x-r,q.y-r,r*2,r*2,5);if(good)this.stones.lineStyle(2,0xffdf87,.9).strokeRoundedRect(q.x-r,q.y-r,r*2,r*2,5);}else{this.stones.fillStyle(0x142a23,.6).fillRoundedRect(q.x-r,q.y-r+5,r*2,r*2,5).fillStyle(bad?0x87595e:[0x7c8771,0x74816a,0x808b72][(p.x+p.y)%3]).fillRoundedRect(q.x-r,q.y-r,r*2,r*2,5).lineStyle(good?3:1,good?0xffd673:0xbdc7a0,good?1:.35).strokeRoundedRect(q.x-r,q.y-r,r*2,r*2,5);this.stones.fillStyle(0x406541,.7).fillRect(q.x-r+3,q.y+r-5,7,3);}if(bad)this.label(q.x+r-9,q.y-r+10,'!','#ffceba',15);if(good)this.stones.fillStyle(0xffdb80,.85).fillCircle(q.x,q.y,4);if(this.best&&same(this.best.to,p))this.label(q.x,q.y,'✧','#ffe99b',28);if(s.level===4&&p.y===4)this.label(q.x,q.y+this.cell*.32,'•','#b6d4df',12);}
 const goal=goalCell(s.level);if(goal){const p=this.point(goal);this.label(p.x,p.y,'★','#ffe6a0',26);}
 for(const [id,sprite] of this.pieces)if(!s.pieces.some(p=>p.id===id)){sprite.destroy();this.pieces.delete(id);}
 for(const p of s.pieces){let sprite=this.pieces.get(p.id);if(!sprite){sprite=this.add.sprite(0,0,this.forest?'forest-pawn':'heroes',0).setDepth(4);this.pieces.set(p.id,sprite);}const q=this.point(p);if(this.forest){this.cast!.apply(sprite,kind(p),p.side==='friend'?'apprentice':(this.gear[kind(p)]??forestTier(this.progress,kind(p))),p.side==='enemy',this.cell);sprite.setPosition(q.x,q.y+this.cell*.45).setData('groundY',q.y+this.cell*.45).setAngle(0);this.label(q.x+this.cell*.31,q.y+this.cell*.36,p.side==='enemy'?'▼':p.side==='friend'?'♡':p.id==='b'?'②':kind(p)==='knight'?'♞':kind(p)==='rook'?'♜':'♙',p.side==='enemy'?'#ecc1ed':'#fff1be',Math.max(9,this.cell*.21));}else{sprite.setFrame(kind(p)==='knight'?1:kind(p)==='rook'?3:0);sprite.setPosition(q.x,q.y).setAngle(0).setDisplaySize(this.cell*1.1,this.cell*1.1).clearTint();if(p.side==='enemy')sprite.setTint(0xaa82d5);else if(p.side==='friend')sprite.setTint(0xf4d888);else if(p.id==='b')sprite.setTint(0xa5dcff);if(p.side==='enemy')this.label(q.x,q.y-this.cell*.4,'▼','#eac1ff',13);if(p.side==='hero')this.label(q.x,q.y+this.cell*.36,kind(p)==='knight'?'♞':'↑','#e6f7cc',13);}if(p.id===this.selected)this.stones.lineStyle(3,0xffdf88).strokeCircle(q.x,q.y,this.cell*.42);}
 const knight=s.pieces.find(p=>p.side==='hero'&&kind(p)==='knight');
 if(s.level===10&&knight&&forkTargets(s,knight).length>=2){const a=this.point(knight);for(const target of forkTargets(s,knight)){const b=this.point(target);if(this.forest)this.stones.lineStyle(2,0xffdc77,.8).strokeCircle(b.x,b.y,this.cell*.4);else this.stones.lineStyle(3,0xffdc77,.9).lineBetween(a.x,a.y,b.x,b.y);this.label(b.x,b.y-this.cell*.38,'!','#ffe28e',22);}}
 if(this.forest){this.dragon.layout(stageX+stageWidth*.10,stageY+stageHeight*.99,Math.min(stageWidth*.18,stageHeight*.11));return;}
 const compact=w<650;this.dragon.layout(compact?w-40:Math.max(100,this.ox-72),compact?this.oy-7:Math.min(h-38,this.oy+this.cell*3.4),compact?Math.min(77,Math.max(45,this.oy-62)):Math.min(165,this.ox-22));
 }
 update(time:number){if(!this.dataState)return;if(this.forest)this.forestFx!.update(time,this.reduced);else this.atmosphere.update(time,this.reduced);this.shadows.clear();for(const p of this.dataState.pieces){const q=this.point(p);const sprite=this.pieces.get(p.id);this.shadows.fillStyle(0x15221f,.3).fillEllipse(this.forest&&sprite?sprite.x:q.x,this.forest&&sprite?(sprite.getData('groundY')??sprite.y):q.y+this.cell*.3,this.cell*.55,this.cell*.16);if(!this.forest&&!this.moving&&!this.reduced){const sprite=this.pieces.get(p.id);if(sprite)sprite.y=q.y+Math.sin(time/430+p.x)*1.3;}}this.dragon.update(time,this.reduced);}
 animate(id:string,from:Cell,to:Cell,capture=false){if(this.forest)return this.animateForest(id,from,to,capture);const sprite=this.pieces.get(id);if(!sprite)return Promise.resolve();this.moving=true;const a=this.point(from),b=this.point(to);return new Promise<void>(resolve=>{const finish=()=>{this.moving=false;this.finishes.delete(finish);sprite.setAngle(0);resolve();};this.finishes.add(finish);this.tweens.addCounter({from:0,to:1,duration:this.reduced?80:capture?550:430,ease:'Sine.easeInOut',onUpdate:t=>{const v=t.getValue()??1;sprite.setPosition(Phaser.Math.Linear(a.x,b.x,v),Phaser.Math.Linear(a.y,b.y,v)-(this.reduced?0:Math.sin(v*Math.PI)*(this.dataState?.pieces.find(p=>p.id===id)?.kind==='knight'?32:8))).setAngle(this.reduced?0:Math.sin(v*Math.PI)*(capture?8:2));},onComplete:()=>{this.atmosphere.burst(b.x,b.y,capture?'hit':'land',this.reduced);finish();}});});}
 private animateForest(id:string,from:Cell,to:Cell,capture:boolean){
  const sprite=this.pieces.get(id),piece=this.dataState?.pieces.find(p=>p.id===id);if(!sprite||!piece)return Promise.resolve();const spec=forestMove(kind(piece),from,to,capture);if(!spec)return Promise.resolve();
  const tier=piece.side==='friend'?'apprentice':(this.gear[kind(piece)]??forestTier(this.progress,kind(piece))),a=this.point(from),b=this.point(to),victim=this.dataState?.pieces.find(p=>p.id!==id&&same(p,to));
  this.forestFx!.start(spec,p=>this.point(p),this.cell,tier,this.reduced,capture);
  if(this.reduced){sprite.setPosition(b.x,b.y+this.cell*.45);return Promise.resolve();}
  if(victim){const target=this.pieces.get(victim.id);if(target)this.forestFx!.capture(target,spec.duration);}
  this.moving=true;let echoed=false;
  return new Promise<void>(resolve=>{const finish=()=>{this.moving=false;this.finishes.delete(finish);sprite.setAngle(0);resolve();};this.finishes.add(finish);
   this.tweens.addCounter({from:0,to:1,duration:spec.duration,ease:'Linear',onUpdate:t=>{
    const v=t.getValue()??1,flight=kind(piece)==='knight'?Math.max(0,(v-.36)/.64):v,lift=kind(piece)==='knight'?Math.sin(flight*Math.PI)*this.cell*.48:kind(piece)==='pawn'?Math.sin(v*Math.PI)*Math.min(4,this.cell*.07):0;
    sprite.setData('groundY',Phaser.Math.Linear(a.y,b.y,flight)+this.cell*.45).setPosition(Phaser.Math.Linear(a.x,b.x,flight),Phaser.Math.Linear(a.y,b.y,flight)+this.cell*.45-lift).setAngle(kind(piece)==='pawn'?Math.sin(v*Math.PI)*3:0);
    if(tier==='master'&&!echoed&&v>.63){echoed=true;this.forestFx!.echo(sprite);}
   },onComplete:finish});
  });
 }
 demo(from:Cell&{kind?:string},to:Cell){const a=this.point(from),b=this.point(to);this.ghost=this.add.sprite(a.x,a.y,'heroes',from.kind==='knight'?1:0).setDisplaySize(this.cell*1.1,this.cell*1.1).setAlpha(.4).setDepth(5);this.stones.lineStyle(3,0xffe28e).beginPath().moveTo(a.x,a.y);if(from.kind==='knight'){if(Math.abs(to.y-from.y)===2)this.stones.lineTo(a.x,b.y);else this.stones.lineTo(b.x,a.y);}this.stones.lineTo(b.x,b.y).strokePath();return new Promise<void>(resolve=>{const finish=()=>{this.ghost?.destroy();this.ghost=undefined;this.finishes.delete(finish);resolve();};this.finishes.add(finish);this.tweens.add({targets:this.ghost,x:b.x,y:b.y,duration:this.reduced?500:1500,ease:'Sine.easeInOut',onComplete:finish});});}
 pause(ms:number){if(this.forest&&this.reduced)return Promise.resolve();return new Promise<void>(resolve=>{const f=()=>{this.finishes.delete(f);resolve();};this.finishes.add(f);this.time.delayedCall(ms,f);});}
 celebrate(){this.dragonCue('happy');if(!this.dataState)return;const p=this.dataState.pieces.find(p=>p.side==='hero');if(p){const q=this.point(p);if(this.forest)this.forestFx!.celebrate(q,this.cell,this.reduced);else this.atmosphere.burst(q.x,q.y,'win',this.reduced);}}
 cancel(){this.dragon?.reset();this.tweens.killAll();this.time.removeAllEvents();for(const f of [...this.finishes])f();this.atmosphere?.clear();this.forestFx?.clear();this.moving=false;}
}
