import {BoardMotion} from '../board-motion';
import {loadViewSettings,saveViewSettings} from '../learning/view-settings';
import {FullGame,restoreGames,legacyGame,type Games} from './model';
import {actor,glyphs,enemyGlyphs} from '../learning/actors';
import {ledger} from '../learning/store';
import {input,status,type Square,type InputMove,type OpponentTier} from '../engine/chess';
import type {Voice} from '../speech';
import './hub.css';
const pieceNames={p:'Pawn',n:'Knight',b:'Bishop',r:'Rook',q:'Queen',k:'King'};
const preview=new URLSearchParams(location.search).get('preview');export const fullKey=preview?'chessia-full-preview-'+preview+'-v1':'chessia-full-game-v1';
let records:Games;try{records=restoreGames(JSON.parse(localStorage.getItem(fullKey)||'null'));}catch{records=restoreGames(null);}
function migrate(id:'akin'|'prin'){if(records.profiles[id]?.current)return;const campaignKey=preview==='forest-adventure'?'chessia-forest-preview-campaign-v1':preview==='rook-grove'?'chessia-rook-preview-campaign-v1':'chessia-campaign-v2';try{const campaign=JSON.parse(localStorage.getItem(campaignKey)||'null')?.[id]?.session;const draft=JSON.parse(localStorage.getItem('chessia-learning-draft-'+id+'-'+(preview??'journey'))||'null');const primary=legacyGame(campaign),secondary=legacyGame(draft),game=primary??secondary;if(game){records.profiles[id]={current:game.save(),previous:primary&&secondary&&primary.match.chess.fen()!==secondary.match.chess.fen()?secondary.save():null};localStorage.setItem(fullKey,JSON.stringify(records));}}catch{}}
export function gameThumbnail(id:'akin'|'prin'){migrate(id);const saved=records.profiles[id]?.current,game=FullGame.restore(saved)??new FullGame(),c=game.match.chess;return `<span class="full-thumbnail" aria-hidden="true">${c.board().flat().map((p,i)=>`<i style="background:${(Math.floor(i/8)+i%8)%2?'#73917b':'#e3d6ad'}">${p?(p.color==='w'?glyphs:enemyGlyphs)[p.type]:''}</i>`).join('')}</span><span class="full-play-icon">${saved&&!c.isGameOver()?'⏵':'▶'}</span><span>${id==='akin'?'Akin':'Prin'}<small>${saved&&!c.isGameOver()?'Resume':'Play'}</small></span>`;}
export function createFullGameHub(voice:Voice){
 const root=document.createElement('section');root.className='full-room';root.hidden=true;root.innerHTML=`<header><button data-home aria-label="Home">⌂<small>Home</small></button><div class="full-turn" role="status"></div><button data-menu aria-label="Game choices">⚙<small>Choices</small></button></header><aside hidden><label>Opponent <select data-tier><option value="gentle">Gentle</option><option value="steady">Steady</option><option value="challenge">Challenge</option></select></label><label><input type="checkbox" data-symbols> Chess symbols</label><label><input type="checkbox" data-motion> Reduce motion</label><button data-new aria-label="New game">＋ ▦ <small>New game</small></button><button data-previous hidden aria-label="Resume previous game">⏵ ▦ <small>Previous game</small></button><p class="full-options-note">New game keeps your previous board. Undo and Help keep your rewards.</p></aside><div class="full-field"><div class="full-board" role="group" aria-label="Full chess board"></div></div><div class="full-promotion" hidden role="group" aria-label="Choose promotion"><strong>Choose a friend</strong>${(['q','r','b','n']as const).map(p=>`<button data-promotion="${p}" aria-label="Promote to ${pieceNames[p]}">${glyphs[p]}<small>${pieceNames[p]}</small></button>`).join('')}<button data-promotion="cancel" aria-label="Cancel promotion">✕<small>Cancel</small></button></div><footer><p class="full-status" aria-live="polite"></p><div class="full-controls"><button data-undo aria-label="Undo your move and AI reply">↶<small>Undo</small></button><button data-help aria-label="Help with your plan">♧<small>Help</small></button><button data-listen aria-label="Listen to turn guidance">◖))<small>Listen</small></button><button data-new-inline hidden aria-label="New game">＋ ▦<small>New game</small></button><button data-retry hidden aria-label="Retry AI">↻<small>Retry AI</small></button></div><small class="full-voice" hidden role="status">Voice unavailable. Follow the glowing squares.</small><small class="full-save" hidden>Saving unavailable. Keep this page open.</small></footer>`;document.body.append(root);
 const icons={home:'<path d="M3 11L12 3l9 8v10h-6v-7H9v7H3Z"/>',help:'<path d="M8 16c0-3-4-4-4-8a8 8 0 0116 0c0 4-4 5-4 8Z M8 20h8M10 23h4"/>',listen:'<path d="M3 9h5l6-5v16l-6-5H3Z M17 8q5 4 0 8M20 5q8 7 0 14"/>',undo:'<path d="M8 5L2 10l6 5M3 10h10a7 7 0 010 14"/>'};for(const [key,path] of Object.entries(icons)){const b=root.querySelector<HTMLElement>('[data-'+(key==='home'?'home':key)+']')!;const label=b.querySelector('small')!.outerHTML;b.innerHTML='<svg viewBox="0 0 26 26" aria-hidden="true">'+path+'</svg>'+label;}
 const $=(s:string)=>root.querySelector<HTMLElement>(s)!;const board=$('.full-board'),menu=$('aside'),line=$('.full-status');
 const motion=new BoardMotion(board,()=>{if(!root.hidden)render();});
 let profile:'akin'|'prin'='akin',game=new FullGame(),selected:Square|null=null,promotion:InputMove|null=null,worker:Worker|null=null,closed:()=>void=()=>{},failed=false,showThreats=false;
 const reduced=root.querySelector<HTMLInputElement>('[data-motion]')!,symbolsControl=root.querySelector<HTMLInputElement>('[data-symbols]')!;
 function loadSettings(){const settings=loadViewSettings(profile);reduced.checked=settings.reducedMotion;symbolsControl.checked=settings.symbols;}
 matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{if(!root.hidden){loadSettings();motion.cancel();render();}});
 let fallbackMissing:Voice['onMissing'];const missingVoice=()=>{fallbackMissing?.();if(!root.hidden)$('.full-voice').hidden=false;};
 function say(text:string){line.textContent=text;voice.say(text);}
 function stop(){motion.cancel();game.cancel();worker?.terminate();worker=null;voice.stop();}
 function save(){const p=records.profiles[profile]??{current:null,previous:null};p.current=game.save();records.profiles[profile]=p;try{localStorage.setItem(fullKey,JSON.stringify(records));$('.full-save').hidden=true;}catch{$('.full-save').hidden=false;}}
 function render(){const c=game.match.chess,end=status(c),action=motion.action,ai=action?action.side==='enemy':c.turn()==='b';root.classList.toggle('full-thinking',game.busy);root.classList.toggle('full-reduced',reduced.checked);$('.full-turn').innerHTML=`<span class="full-avatar">${actor('k',ai,ledger.evidence(profile,'k').owned)}</span><strong>${action?(ai?'AI':profile==='akin'?'Akin':'Prin'):game.busy?'◌ AI':c.isGameOver()?'⚑':ai?'AI':profile==='akin'?'Akin':'Prin'}</strong><small>${action?pieceNames[action.role]+(action.capture?' takes':' moves'):game.busy?'Thinking':c.isGameOver()?end:ai?'Their turn':'Your turn'}</small>`;
 root.querySelector<HTMLSelectElement>('[data-tier]')!.value=game.tier;$('[data-previous]').hidden=!records.profiles[profile]?.previous;
 board.replaceChildren();const symbols=symbolsControl.checked,landings=selected?c.moves({square:selected,verbose:true}).map(m=>m.to):[];
 for(let rank=8;rank>=1;rank--)for(const file of 'abcdefgh'){const sq=(file+rank)as Square,p=c.get(sq),b=document.createElement('button');b.dataset.square=sq;b.className='full-cell '+((rank+file.charCodeAt(0))%2?'light':'dark');b.setAttribute('aria-label',sq+(p?' '+(p.color==='w'?'White':'Black')+' '+pieceNames[p.type]:''));b.setAttribute('aria-pressed',String(sq===selected));b.disabled=motion.active||game.busy||ai||c.isGameOver()||!!promotion;if(p){b.classList.add(p.color==='w'?'friend':'enemy');const glyph=(p.color==='w'?glyphs:enemyGlyphs)[p.type];b.innerHTML=symbols?`<span class="full-symbol">${glyph}</span>`:actor(p.type,p.color==='b',ledger.evidence(profile,p.type).owned)+`<span class="chess-bridge">${glyph}</span>`;}b.innerHTML+=`<span class="full-coordinate">${sq}</span>`;if(sq===selected)b.classList.add('selected');if(landings.includes(sq))b.classList.add('landing');if(p?.type==='k'&&p.color===c.turn()&&c.isCheck())b.classList.add('checked');if(showThreats&&p?.color==='w'&&c.attackers(sq,'b').length)b.classList.add('threat');b.onclick=()=>tap(sq);board.append(b);}
 ($('[data-undo]')as HTMLButtonElement).disabled=!c.history().length;$('[data-retry]').hidden=!failed;$('.full-promotion').hidden=!promotion;$('[data-new-inline]').hidden=!c.isGameOver();
 if(!failed)line.textContent=action?`${ai?'AI':profile==='akin'?'Akin':'Prin'}'s ${pieceNames[action.role]} ${action.capture?'takes a guard':'moves'}.`:c.isGameOver()?end==='checkmate'?`⚑ Checkmate · ${c.turn()==='w'?'AI':'You'} won. Undo or New game.`:`⚑ Draw · ${end}. Undo or New game.`:game.busy?'◌ AI is thinking…':promotion?'↑ Choose a friend for your pawn.':selected?`${pieceNames[c.get(selected)!.type]} selected. ${landings.length?'Tap a glowing square.':'No safe landing. Try another friend.'}`:c.isCheck()?'⚠ Check — protect the red-ringed King.':showThreats?'⚠ Red rings show attacked friends. Choose a safe move.':'☝ Tap your friend, then a square.';
 motion.refresh();
 }
 function reply(){if(root.hidden)return;worker?.terminate();worker=null;const active=game,ticket=game.request();if(!ticket){render();return;}failed=false;save();render();let w:Worker;try{w=new Worker(new URL('../engine/opponent.worker.ts',import.meta.url),{type:'module'});}catch{active.cancel();failed=true;save();render();say('AI could not load. Tap Retry AI.');return;}worker=w;w.onmessage=async e=>{await motion.settled();if(root.hidden||game!==active||worker!==w||e.data.id!==ticket.id)return;const shots=motion.snapshot(),moved=active.accept(ticket,e.data.move);w.terminate();worker=null;if(!moved){failed=true;say('AI could not move. Tap Retry AI.');}save();render();if(moved)void motion.play(moved,shots,reduced.checked||symbolsControl.checked);};w.onerror=()=>{if(game!==active||worker!==w)return;active.cancel();w.terminate();worker=null;failed=true;save();render();say('AI could not load. Tap Retry AI.');};w.postMessage({id:ticket.id,save:ticket.save,tier:ticket.tier});}
 function play(move:InputMove){const shots=motion.snapshot(),played=game.play(move);if(!played)return;selected=null;promotion=null;failed=false;showThreats=false;save();render();voice.sound(game.match.chess.isGameOver());void motion.play(played,shots,reduced.checked||symbolsControl.checked);reply();}
 function tap(sq:Square){const c=game.match.chess;if(motion.active||game.busy||c.turn()!=='w'||promotion)return;if(c.get(sq)?.color==='w'){selected=sq;render();return;}if(!selected){say('Tap your friend first.');return;}const moves=c.moves({square:selected,verbose:true}).filter(m=>m.to===sq);if(!moves.length){say('That square does not work. Choose another.');return;}if(moves.some(m=>m.promotion)){promotion={from:selected,to:sq};render();$('[data-promotion="q"]').focus();return;}play(input(moves[0]));}
 $('[data-home]').onclick=()=>{stop();save();root.hidden=true;if(voice.onMissing===missingVoice)voice.onMissing=fallbackMissing;closed();};$('[data-menu]').onclick=()=>{menu.hidden=!menu.hidden;};$('[data-undo]').onclick=()=>{stop();game.undo();selected=null;promotion=null;failed=false;showThreats=false;save();render();};$('[data-help]').onclick=()=>{showThreats=true;render();say(game.match.chess.isCheck()?'Red ring: your king is attacked. Move, block, or take the attacker.':'Red rings show attacked friends. Keep them safe, then improve one piece.');};$('[data-listen]').onclick=()=>voice.say(line.textContent??'Your turn.');$('[data-retry]').onclick=reply;
 $('[data-new-inline]').onclick=()=>($('[data-new]')as HTMLButtonElement).click();$('[data-new]').onclick=()=>{stop();const previous=game.save();records.profiles[profile]={current:null,previous};game=new FullGame(game.tier);selected=null;promotion=null;failed=false;showThreats=false;menu.hidden=true;save();render();};$('[data-previous]').onclick=()=>{const old=FullGame.restore(records.profiles[profile]?.previous);if(!old)return;stop();const previous=game.save();game=old;records.profiles[profile]={current:game.save(),previous};selected=null;promotion=null;failed=false;showThreats=false;menu.hidden=true;save();render();reply();};
 root.querySelector<HTMLSelectElement>('[data-tier]')!.onchange=e=>{stop();game.tier=(e.target as HTMLSelectElement).value as OpponentTier;save();render();reply();};symbolsControl.onchange=()=>{motion.cancel();saveViewSettings(profile,{symbols:symbolsControl.checked});render();};reduced.onchange=()=>{motion.cancel();saveViewSettings(profile,{reducedMotion:reduced.checked});render();};
 $('.full-promotion').onclick=e=>{const choice=(e.target as HTMLElement).closest<HTMLElement>('[data-promotion]')?.dataset.promotion;if(!choice||!promotion)return;if(choice==='cancel'){promotion=null;render();return;}play({...promotion,promotion:choice as InputMove['promotion']});};
 window.addEventListener('pagehide',()=>{if(!root.hidden){stop();save();}});window.addEventListener('resize',()=>{if(!root.hidden){motion.cancel();render();}});
 return (id:'akin'|'prin',onClose:()=>void,tier?:OpponentTier)=>{stop();profile=id;loadSettings();if(voice.onMissing!==missingVoice)fallbackMissing=voice.onMissing;voice.onMissing=missingVoice;$('.full-voice').hidden=true;closed=onClose;migrate(id);game=FullGame.restore(records.profiles[id]?.current)??new FullGame(tier);if(tier)game.tier=tier;selected=null;promotion=null;failed=false;showThreats=false;root.hidden=false;menu.hidden=true;save();render();reply();};
}
