import Phaser from 'phaser';
import './style.css';
import { Shrine } from './renderer';
import { LessonGame, LESSONS, cells, same, GOALS, type Stage, type Cell } from './simulation';
import { GameAudio, cues } from './audio';
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const sim=new LessonGame(),audio=new GameAudio(),scene=new Shrine();
let busy=false,epoch=0,completed:boolean[]=[false,false,false];
try{const v=JSON.parse(localStorage.getItem('chessia-shrine-v1')||'null');if(Array.isArray(v)&&v.length===3)completed=v.map(x=>x===true);}catch{}
scene.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
el<HTMLInputElement>('reduce-motion').checked=scene.reduced;
const controls=cells.map((p,i)=>{const b=document.createElement('button');b.className='cell-control';b.tabIndex=i===25?0:-1;b.dataset.cell=`${p.x},${p.y}`;b.addEventListener('click',()=>void choose(p));b.addEventListener('keydown',e=>{const d:Record<string,number>={ArrowLeft:-1,ArrowRight:1,ArrowUp:-6,ArrowDown:6};if(e.key in d){e.preventDefault();const j=i+d[e.key];if(j>=0&&j<36&&(Math.abs(d[e.key])===6||Math.floor(j/6)===p.y)){controls.forEach(x=>x.tabIndex=-1);controls[j].tabIndex=0;controls[j].focus();}}});el('cell-controls').append(b);return b;});
scene.layout=(x,y,c)=>controls.forEach((b,i)=>Object.assign(b.style,{left:`${x+cells[i].x*c}px`,top:`${y+cells[i].y*c}px`,width:`${c}px`,height:`${c}px`}));
function say(id:keyof typeof cues){el('message').textContent=cues[id];audio.say(id);}
function update(render=true){const s=sim.state;if(render)scene.sync(sim.snapshot);el('lesson-name').textContent=LESSONS[s.stage].name;el('intro').hidden=s.phase!=='intro';el('intro-title').textContent=LESSONS[s.stage].name;el('intro-copy').textContent=['Watch the knight. Then try a jump.','Reach the star. Watch the straight lines from the golem.','Jump to capture the golem. Hints are always here.'][s.stage];el('turn-text').textContent=({intro:'Let us help our friend',demo:'Watch the knight',player:'Your turn',enemy:'Golem turn',won:'You did it!',lost:'Try again'} as const)[s.phase];el('turn-icon').textContent=s.phase==='enemy'?'♜':s.phase==='won'?'★':'♘';el<HTMLButtonElement>('undo').disabled=!sim.canUndo;el<HTMLButtonElement>('hint').disabled=busy||s.phase!=='player';el<HTMLButtonElement>('settings').disabled=busy;el('next').hidden=s.phase!=='won'||busy;el('next').textContent=s.stage===2?'Play again ↻':'Next →';el('danger-legend').hidden=!s.rook;el('scene-notice').hidden=s.phase!=='lost';el('scene-notice').textContent='↶ Undo and try again';controls.forEach((b,i)=>{b.disabled=busy||s.phase!=='player';b.setAttribute('aria-label',`Square ${cells[i].x+1}, ${cells[i].y+1}${same(cells[i],s.knight)?' Knight':same(cells[i],s.rook)?' Golem':''}`);});document.querySelectorAll<HTMLButtonElement>('[data-stage]').forEach(b=>{const n=Number(b.dataset.stage);b.disabled=busy||(n>0&&!completed[n-1]);b.classList.toggle('current',n===s.stage);b.setAttribute('aria-current',n===s.stage?'step':'false');});}
function finish(){if(sim.state.phase==='won'){completed[sim.state.stage]=true;try{localStorage.setItem('chessia-shrine-v1',JSON.stringify(completed));}catch{el('save-note').textContent='This browser cannot save your progress.';}scene.celebrate();audio.effect('win');say(sim.state.stage===2?'complete':'success');}else if(sim.state.phase==='lost')say('lost');else say('yourTurn');}
async function choose(p:Cell){if(busy||sim.state.phase!=='player')return;audio.unlock();if(same(p,sim.state.knight)){sim.select();audio.effect('tap');say('choose');update();return;}if(same(p,sim.state.rook)&&!sim.state.selected){sim.inspectEnemy();say('danger');update();return;}if(!sim.state.selected){say('tapKnight');return;}const action=sim.move(p);if(!action.accepted){say('invalid');return;}const turn=++epoch;busy=true;update(false);audio.effect('jump');await scene.animate('knight',action.from!,p);if(turn!==epoch)return;if(action.capture){audio.effect('hit');scene.impact(p);}scene.sync(sim.snapshot);if(sim.snapshot.phase==='enemy'){say('enemy');await scene.pause(450);if(turn!==epoch)return;const from=sim.state.rook!;sim.reply();await scene.animate('rook',from,sim.state.rook!);if(turn!==epoch)return;if(!sim.state.alive){audio.effect('hit');scene.impact(sim.state.knight);}}busy=false;finish();update();}
function reset(stage:Stage){epoch++;scene.cancel();audio.stop();busy=false;sim.reset(stage);say('welcome');update();}
el('begin').onclick=async()=>{audio.unlock();sim.begin();const turn=++epoch;if(sim.state.phase==='demo'){busy=true;update();say('demo');scene.route(sim.state.knight,GOALS[0]);await scene.pause(1600);if(turn!==epoch)return;await scene.animate('knight',sim.state.knight,GOALS[0]);if(turn!==epoch)return;await scene.pause(3000);if(turn!==epoch)return;sim.finishDemo();busy=false;say('tapKnight');}else say(LESSONS[sim.state.stage].cue);update();};
el('undo').onclick=()=>{epoch++;scene.cancel();audio.stop();busy=false;if(sim.undo())say('undo');update();};
el('hint').onclick=()=>{sim.hint();sim.select();say(sim.state.hints===3?'hintPath':sim.state.hints===2?'hintDanger':'hint');update();};
el('next').onclick=()=>reset(((sim.state.stage+1)%3) as Stage);
document.querySelectorAll<HTMLButtonElement>('[data-stage]').forEach(b=>b.onclick=()=>reset(Number(b.dataset.stage) as Stage));
el('replay-voice').onclick=()=>{audio.unlock();audio.say(audio.last);};
function sound(){el('sound').textContent=audio.enabled?'♫':'♪̸';el('sound').setAttribute('aria-pressed',String(audio.enabled));el('sound').setAttribute('aria-label',audio.enabled?'Mute sound':'Unmute sound');}sound();el('replay-icon').textContent='♫';
el('sound').onclick=()=>{audio.enabled=!audio.enabled;audio.unlock();if(!audio.enabled)audio.stop();sound();};
const dialog=el<HTMLDialogElement>('settings-dialog');el('settings').onclick=()=>dialog.showModal();el('close-settings').onclick=()=>dialog.close();el('restart').onclick=()=>{dialog.close();reset(sim.state.stage);};el('reduce-motion').onchange=()=>{scene.reduced=el<HTMLInputElement>('reduce-motion').checked;document.body.classList.toggle('reduced-motion',scene.reduced);};
audio.onUnavailable=()=>{el('message-label').textContent='No English voice. Watch the pictures and try.';el('save-note').textContent='No English voice is ready on this device.';};
scene.ready=()=>update();new Phaser.Game({type:Phaser.AUTO,parent:'canvas-host',backgroundColor:'#213d30',pixelArt:true,scale:{mode:Phaser.Scale.RESIZE,width:el('canvas-host').clientWidth,height:el('canvas-host').clientHeight},scene:[scene],audio:{noAudio:true}});
